version: '3.8'

services:
  ollama:
    image: ubuntu:22.04
    container_name: ollama-server
    entrypoint: >
      sh -c "curl -fsSL https://ollama.com/install.sh | bash \
             && ollama pull llama3 \
             && ollama serve --host 0.0.0.0"
    ports:
      - "11434:11434"      # domyślny port Ollama
    volumes:
      - ollama-data:/root/.ollama

  fastapi:
    build: .
    container_name: fastapi-app
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434

volumes:
  ollama-data:
